### ISSUE TITLE
Tracking: ProjFS regression with buffer resizing

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/VFSForGit#1696]
While working on the GIt 2.29.0 update, we noticed that projections were failing to match vanilla Git when it came to the `GVFlt_MoveFileTests/LongFileName` folder. The root cause is that ProjFS updated recently in response to a security bug, but that fix included a change to how it handles resizing filename buffers.

With the help of @wilbaker and @cgallred, we discovered the root cause, and the ProjFS team is working on a fix.

In order to get us unblocked, we need to stop testing this scenario until ProjFS ships to the Azure Pipelines build machines.

1. [X] Remove the `GVFlt_MoveFileTests/LongFileName` folder in the test repo (using new branch `FunctionalTests/20201014`)
2. [ ] Point VFS for Git functional tests to that branch, and ignore any tests that care about that folder.
3. [ ] Periodically check if we can revert that change to the functional tests.
4. [ ] Revert the test changes.

**Comment by iamhardikat11** [comment]
I am Novice Open Source Programmer, looking contribute to this Repository, can you please describer more on this issue?

**Comment by derrickstolee** [comment]
Hi @iamhardikat11: the cause of this bug was in a low-level driver included in Windows (and is not open source). The only action here is to revert #1697, assuming that the GitHub Actions workflow runners have updated to a version of Windows with the fix.

Overall, this repository is in maintenance mode, so I don't think it's a good fit for learning about open source contributions.

**Comment by iamhardikat11** [comment]
Ok Thank You.
