### ISSUE TITLE
Enable ability to customize VFSForGit Upgrade

### ISSUE THREAD

**Issue by jamill** [Microsoft/VFSForGit#717]
This issue tracks the different parts of the work to make VFSForGit upgrade extensible. This extensibility can be used by organizations to custom the VFSForGit upgrade process to meet their specific requirements.

## Design Doc
#547

## Initial changes to enable feature
#674 

## TODO - Required
- [ ] Verify Nuget Package signature
- [ ] Limit access to temp file directories
- [ ] Limit access to GVFS.Config
- [ ] Anonymous polling for available updates

## TODO - Nice to have
- [ ] Add concept of "minimum version allowed to upgrade from"

## Associated issues
#704

**Comment by wilbaker** [comment]
Other nice to haves:

- Update unit tests to validate that VFS4G code that writes new version to a marker file is writing the expected version.  Currently it only validates that VFS4G has written something.

- Cleanup PhysicalFileSystem and IPlatformFileSystem.  Their interaction (and how they differ) is not clear, and the more we add to them the more confusing it becomes.

- Switch from calling `Exit` to letting unhandled exceptions bring down the process.  Some investigation is required to makes sure that all native\background threads with unhandled exceptions will crash the VFS4G process.

**Comment by wilbaker** [comment]
- Cleanup `PhysicalFileSystem.DeleteDirectory` it currently just calls `RecusiveDelete`, so why have both?

**Comment by wilbaker** [comment]
- Update upgrade functional tests to use Test.GVFS.Upgrade folder rather than GVFS.Upgrade

**Comment by wilbaker** [comment]
Cleanup `gvfs log` so that file paths are all aligned in the same column.  Currently it looks like this:

```\E:\repo6>gvfs log
Most recent log files:
  clone     : E:\repo6\.gvfs\logs\gvfs_clone_20181024_094528.log
  mount     : E:\repo6\.gvfs\logs\gvfs_mount_verb_20190130_140733.log
  prefetch  : E:\repo6\.gvfs\logs\gvfs_prefetch_20181024_094548.log
  dehydrate : None
  repair    : E:\repo6\.gvfs\logs\gvfs_repair_20181105_163128.log
  service   : C:\ProgramData\GVFS\GVFS.Service\Logs\gvfs_service_20190207_143020.log
  productupgrade: C:\ProgramData\GVFS\GVFS.Upgrade\Logs\gvfs_productupgrade_process_20190207_144030.log

```

@jrbriggs FYI - This is the work item I've been using for collecting upgrader follow up work items.

**Comment by jrbriggs** [comment]
@wilbaker I have spun out #755 #756 #757 #758 #759 #760 as carry-over work. I'm going to close this issue since it was tracking the work delivered in #748.
